import { JsonFragment } from '@ethersproject/abi';
declare const IERC20: JsonFragment[];
declare const Multicall2: JsonFragment[];
declare const Banana: JsonFragment[];
declare const BananaClaimable: JsonFragment[];
declare const Pair: JsonFragment[];
declare const TWAMMInstantSwap: JsonFragment[];
declare const IMerkleDistributor: JsonFragment[];
declare const BuybackPool: JsonFragment[];
declare const IEsAPEX2: JsonFragment[];
declare const StakingPool2: JsonFragment[];
export { IERC20, Multicall2, Banana, BananaClaimable, Pair, TWAMMInstantSwap, IMerkleDistributor, BuybackPool, IEsAPEX2, StakingPool2 };
