import { JsonFragment } from '@ethersproject/abi';
export declare const IERC20: JsonFragment[];
export declare const Multicall2: JsonFragment[];
export declare const Banana: JsonFragment[];
export declare const BananaClaimable: JsonFragment[];
export declare const Pair: JsonFragment[];
export declare const TWAMMInstantSwap: JsonFragment[];
export declare const IMerkleDistributor: JsonFragment[];
export declare const BuybackPool: JsonFragment[];
export declare const IEsAPEX2: JsonFragment[];
export declare const StakingPool2: JsonFragment[];
export declare const ApeXPool2: JsonFragment[];
export declare const BananaUsdtPair: JsonFragment[];
export declare const DivineDragoNft: JsonFragment[];
export declare const DragonBall: JsonFragment[];
export declare const DragonBallConfig: JsonFragment[];
export declare const DragonBallNft: JsonFragment[];
